name: Test Firefox Installer

on:
  workflow_dispatch:
    inputs:
      browser-version:
        description: Firefox version to install
        required: false
        type: string
        default: 'latest'
  workflow_call:
    inputs:
      browser-version:
        description: Firefox version to install
        required: false
        type: string
        default: 'latest'

jobs:
  bazel:
    name: Test Firefox Installer
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup Firefox
        uses: ali-security/setup-browser@4e1f810b3f116cfc7db1964e8c753272ac2c10d1
        with:
          browser: firefox
          version: ${{ inputs.browser-version }}
      
      - name: Verify Firefox Installation
        run: |
          firefox --version
          echo "Firefox installed successfully!"

