name: Test Firefox Installer

on:
  workflow_dispatch:
    inputs:
      browser-version:
        description: Firefox version to install
        required: false
        type: string
        default: 'latest'
  workflow_call:
    inputs:
      browser-version:
        description: Firefox version to install
        required: false
        type: string
        default: 'latest'

jobs:
  bazel:
    name: Test Firefox Installer
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup Firefox
        uses: abhi1693/setup-browser@v0.3.5
        with:
          browser: firefox
          version: "110.0"
      
      - name: Verify Firefox Installation
        run: |
          firefox --version
          echo "Firefox installed successfully!"

